server:
  port: 8080
spring:
  mvc:
    view:
      prefix: /jsp/
      suffix: .jsp
    static-path-pattern: /static/**
  datasource:
    url: jdbc:mysql://localhost:3306/xindongfang?useSSL=true&serverTimezone=Asia/Shanghai&characterEncoding=UTF8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root


